import { AiFillStar } from "react-icons/ai";



const data = [
  {
    img: "https://m.media-amazon.com/images/I/71At0JjYgCL._AC_UL480_QL65_T2F_.jpg",
    title: "White Monarch IV",
    star: <AiFillStar className="rating-star" />,
    reviews: "(132 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "Form 1",
    color: "white",
    category: "In box",
  },
  {
    img: "https://m.media-amazon.com/images/I/71ozhx4BgcL._AC_UL480_QL65_T2F_.jpg",
    title: "Red  Plus",
    star: <AiFillStar className="rating-star" />,
    reviews: "(103 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "Form 1",
    color: "red",
    category: "Other",
  },

  {
    img: "https://m.media-amazon.com/images/I/714BnwqXeWL._AC_UL480_QL65_T2F_.jpg",
    title: "Random One Sneaker",
    star: <AiFillStar className="rating-star" />,
    reviews: "(193 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "Form 1",
    color: "green",
    category: "Other",
  },
  {
    img: "https://m.media-amazon.com/images/I/71Rgjo8mG2L._AC_UL480_QL65_T2F_.jpg",
    title: "Black and red",
    star: <AiFillStar className="rating-star" />,
    reviews: "(223 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "Form 2",
    color: "black",
    category: "Other",
  },
  {
    img: "https://m.media-amazon.com/images/I/71Iw2VCGmGL._AC_UL480_FMwebp_QL65_.jpg",
    title: "Green Pumps",
    star: <AiFillStar className="rating-star" />,
    reviews: "(120 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "Form 4",
    color: "green",
    category: "Random",
  },
  {
    img: "https://m.media-amazon.com/images/I/71e2Dw-iCBL._AC_UL480_QL65_T2F_.jpg",
    title: "Random color",
    star: <AiFillStar className="rating-star" />,
    reviews: "(523 reviews)",
    prevPrice: "$140,00",
    newPrice: "50",
    company: "Form 2",
    color: "black",
    category: "Random",
  },

  {
    img: "https://m.media-amazon.com/images/I/71HekIcuCZL._AC_UL480_QL65_T2F_.jpg",
    title: "Loafer White",
    star: <AiFillStar className="rating-star" />,
    reviews: "(193 reviews)",
    prevPrice: "$140,00",
    newPrice: "50",
    company: "Form 4",
    color: "white",
    category: "Random",
  },

  {
    img: "https://m.media-amazon.com/images/I/61MFzKqFy1L._AC_UL480_FMwebp_QL65_.jpg",
    title: "Grenn Zoom Freak",
    star: <AiFillStar className="rating-star" />,
    reviews: "(923 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "Form 1",
    color: "green",
    category: "Other",
  },

  {
    img: "https://m.media-amazon.com/images/I/711LCmYVwyL._AC_UL480_QL65_T2F_.jpg",
    title: "Beatiful secret",
    star: <AiFillStar className="rating-star" />,
    reviews: "(183 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "Form 2",
    color: "blue",
    category: "Other",
  },

  {
    img: "https://m.media-amazon.com/images/I/61OMuGArFoL._AC_UL480_QL65_T2F_.jpg",
    title: "White BLACK-OCE",
    star: <AiFillStar className="rating-star" />,
    reviews: "(823 reviews)",
    prevPrice: "$140,00",
    newPrice: "150",
    company: "Form 3",
    color: "green",
    category: "Other",
  },
  {
    img: "https://m.media-amazon.com/images/I/71mQGMciDbL._AC_UL480_QL65_T2F_.jpg",
    title: "Red Future Sneaker",
    star: <AiFillStar className="rating-star" />,
    reviews: "(163 reviews)",
    prevPrice: "$140,00",
    newPrice: "150",
    company: "Form 3",
    color: "red",
    category: "Other",
  },
  {
    img: "https://m.media-amazon.com/images/I/81ED9qSyc-L._AC_UL480_QL65_T2F_.jpg",
    title: "Black Unisex Super",
    star: <AiFillStar className="rating-star" />,
    reviews: "(623 reviews)",
    prevPrice: "$140,00",
    newPrice: "150",
    company: "Form 3",
    color: "black",
    category: "Other",
  },
  {
    img: "https://m.media-amazon.com/images/I/61xhg0wnC8L._AC_UL480_QL65_T2F_.jpg",
    title: "White Basic ",
    star: <AiFillStar className="rating-star" />,
    reviews: "(623 reviews)",
    prevPrice: "$140,00",
    newPrice: "150",
    company: "Form 3",
    color: "white",
    category: "Other",
  },
  {
    img: "https://m.media-amazon.com/images/I/516JO1P0ExL._AC_UL480_QL65_T2F_.jpg",
    title: "Some Future Doubleknit",
    star: <AiFillStar className="rating-star" />,
    reviews: "(333 reviews)",
    prevPrice: "$140,00",
    newPrice: "150",
    company: "Form 3",
    color: "black",
    category: "Other",
  },

  {
    img: "https://m.media-amazon.com/images/I/51sGqnd8PpL.jpg",
    title: "Fusion green",
    star: <AiFillStar className="rating-star" />,
    reviews: "(103 reviews)",
    prevPrice: "$140,00",
    newPrice: "100",
    company: "Form 3",
    color: "green",
    category: "Other",
  },
  {
    img: "https://m.media-amazon.com/images/I/61yx77tDoFL._AC_UL480_FMwebp_QL65_.jpg",
    title: "Rainbow Box",
    star: <AiFillStar className="rating-star" />,
    reviews: "(423 reviews)",
    prevPrice: "$140,00",
    newPrice: "100",
    company: "Form 4",
    color: "red",
    category: "Random",
  },
  {
    img: "https://m.media-amazon.com/images/I/61UMFI7oj-L._AC_UL480_QL65_T2F_.jpg",
    title: "Low-Top Box",
    star: <AiFillStar className="rating-star" />,
    reviews: "(223 reviews)",
    prevPrice: "$140,00",
    newPrice: "100",
    company: "Form 4",
    color: "white",
    category: "In box",
  },
  {
    img: "https://m.media-amazon.com/images/I/51djJ8dVHDL._AC_UL480_QL65_T2F_.jpg",
    title: "Blue Unisex Top",
    star: <AiFillStar className="rating-star" />,
    reviews: "(823 reviews)",
    prevPrice: "$140,00",
    newPrice: "100",
    company: "Form 4",
    color: "blue",
    category: "In box",
  },
  {
    img: "https://m.media-amazon.com/images/I/711ILRCrC3L._AC_UL480_QL65_T2F_.jpg",
    title: "Classic box",
    star: <AiFillStar className="rating-star" />,
    reviews: "(223 reviews)",
    prevPrice: "$140,00",
    newPrice: "50",
    company: "Form 1",
    color: "black",
    category: "In box",
  },
  {
    img: "https://m.media-amazon.com/images/I/71XZ1SRh1AL._AC_UL480_QL65_T2F_.jpg",
    title: "Blacky High box ",
    star: <AiFillStar className="rating-star" />,
    reviews: "(193 reviews)",
    prevPrice: "$140,00",
    newPrice: "50",
    company: "Form 4",
    color: "black",
    category: "Original",
  },
  {
    img: "https://m.media-amazon.com/images/I/61uAs9b1K4L._AC_UL480_QL65_T2F_.jpg",
    title: "Slip On Stiletto flowers",
    star: <AiFillStar className="rating-star" />,
    reviews: "(987 reviews)",
    prevPrice: "$140,00",
    newPrice: "100",
    company: "Form 3",
    color: "black",
    category: "Original",
  },
  {
    img: "https://m.media-amazon.com/images/I/61gyaNsy9QL._AC_UL480_QL65_T2F_.jpg",
    title: "DREAM PAIRS ",
    star: <AiFillStar className="rating-star" />,
    reviews: "(183 reviews)",
    prevPrice: "$140,00",
    newPrice: "150",
    company: "Form 1",
    color: "red",
    category: "Original",
  },
  {
    img: "https://m.media-amazon.com/images/I/71jiLdeoNOL._AC_UL480_QL65_T2F_.jpg",
    title: "Life white and red",
    star: <AiFillStar className="rating-star" />,
    reviews: "(553 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "Form 1",
    color: "red",
    category: "Other",
  },

  {
    img: "https://m.media-amazon.com/images/I/61EHSE9juPL._AC_UL480_QL65_T2F_.jpg",
    title: "Low Mid Green",
    star: <AiFillStar className="rating-star" />,
    reviews: "(233 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "Form 1",
    color: "black",
    category: "Original",
  },
  {
    img: "https://m.media-amazon.com/images/I/71IeR4j53SL._AC_UL480_QL65_T2F_.jpg",
    title: "Chunky Black",
    star: <AiFillStar className="rating-star" />,
    reviews: "(143 reviews)",
    prevPrice: "$140,00",
    newPrice: "50",
    company: "Form 1",
    color: "black",
    category: "Original",
  },
  {
    img: "https://m.media-amazon.com/images/I/81PfC-Zdv1L._AC_UL480_QL65_T2F_.jpg",
    title: "Fashion Stilettos",
    star: <AiFillStar className="rating-star" />,
    reviews: "(663 reviews)",
    prevPrice: "$140,00",
    newPrice: "150",
    company: "Form 1",
    color: "white",
    category: "Original",
  },
  {
    img: "https://m.media-amazon.com/images/I/51z30xutiVL._AC_UL480_QL65_T2F_.jpg",
    title: "Bridal Black",
    star: <AiFillStar className="rating-star" />,
    reviews: "(253 reviews)",
    prevPrice: "$140,00",
    newPrice: "50",
    company: "Form 1",
    color: "black",
    category: "Original",
  },
  {
    img: "https://m.media-amazon.com/images/I/71F0PSFVf8L._AC_UL480_QL65_T2F_.jpg",
    title: "Black Prom Bridal",
    star: <AiFillStar className="rating-star" />,
    reviews: "(122 reviews)",
    prevPrice: "$140,00",
    newPrice: "50",
    company: "Form 2",
    color: "black",
    category: "Random",
  },
];

export default data;


